# Generated by Django 5.0.4 on 2024-04-29 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medinet_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='Practitioner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medinet_backend.practitioner'),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.IntegerField(),
        ),
    ]
