# Generated by Django 5.0.4 on 2024-04-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medinet_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Desease',
            new_name='Disease',
        ),
    ]
