# Generated by Django 3.2.19 on 2024-04-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medinet_backend', '0002_rename_desease_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='occupation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='occupation',
            field=models.CharField(max_length=100),
        ),
    ]
