# Generated by Django 3.2.19 on 2024-04-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medinet_backend', '0003_auto_20240422_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practitioner',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='occupation',
        ),
    ]
