# Generated by Django 5.0.4 on 2024-04-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medinet_backend', '0003_practitioner_dob_practitioner_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='occupation',
        ),
    ]
