# Generated by Django 3.2.19 on 2024-04-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medinet_backend', '0004_auto_20240422_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
    ]
